# Build stage
FROM golang:1.24.6 AS builder

WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/server

# Final image
FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/server .

EXPOSE 9000
ENTRYPOINT ["./server"]
